### PR TITLE
Drop Python 3.4 support; add support for Python 3.7 and above

### PR DESCRIPTION
**Pull request by Mystic-Mirage**
Hi!

We're using asyncio-time-travel in our project with Python 3.5 and we're going to migrate to Python 3.8

Some changes needed to support Python 3.7 and above

### CODE REVIEW

**Comment by realcr** [comment]
@Mystic-Mirage: Thanks for this pull request!
I don't have much free time lately to maintain this package. If you have a project that relies on this package, would you like to take ownership?

**Comment by Mystic-Mirage** [comment]
> I don't have much free time lately to maintain this package. If you have a project that relies on this package, would you like to take ownership?

@realcr Yes, if you don't mind. Also, I need an upload permission for PyPI

**Comment by Mystic-Mirage** [comment]
@realcr You can just add me as a maintainer/collaborator without full ownership transfer. Up to you though.

**Comment by realcr** [comment]
Hey, sorry for the delayed reply, I just found out how to do everything.
You were given owner permissions on PyPI, and I promoted you to be a collaborator on github.  Changing repository's ownership on github seems to be an aggressive operation, so I wanted to make sure everything works well for you before I do it.   

Please confirm that everything works as expected, and I will give you the respository's ownership on github.

**Comment by Mystic-Mirage** [comment]
Hi! PyPI shows me I am an owner now. Didn't find how to check my role on GitHub but a lot of actions now available like creating a new release or setup automation. Looks everything is going right.

**Comment by Mystic-Mirage** [comment]
The only thing I am not able to do it's to change project settings.

**Comment by realcr** [comment]
@Mystic-Mirage : Ownership is now being transferred to you. I hope you will do great things with this repository. Good luck!

**Comment by Mystic-Mirage** [comment]
@realcr Thank you!

**Pull request merged**
